[theme]
base = "light"
primaryColor = "#B95132"
backgroundColor = "#F8F6F0"
secondaryBackgroundColor = "#EEECE3"
textColor = "#292E29"
font = "sans serif"

[server]
address = "127.0.0.1"
port = 8501
headless = true

[browser]
gatherUsageStats = false

